<?php
use Drupal\Core\Render\Markup;
/**
 * @file
 * Main file for hooks and custom functions.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function dummy_preprocess_html(&$variables) {
  \Drupal::service('dummy.random_drupal_message')->setRandomMessage();
}

/**
 * @file
 * Twig template for render content
 */
function dummy_theme($existing, $type, $theme, $path) {

  return [
    'dummy_theme' => [
      'variables' => [
        'list' => [],
      ],
    ],
  ];
}
