<?php

use Drupal\my_events\Event\SaveNodeEvent;

/**
 * Implements hook_entity_update().
 */
function my_events_entity_update(\Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node') {
    /** @var \Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher $dispatcher */
    $dispatcher = \Drupal::service('event_dispatcher');
    // Create event object passing arguments.
    $event = new SaveNodeEvent($entity);
    // Call it.
    $dispatcher->dispatch(SaveNodeEvent::SAVE_NODE, $event);
}

}
